### ISSUE TITLE
Raw data provided by user should be validated better before it is used.

### ISSUE THREAD

**Issue by danmarsden** [Panopto/Moodle-Panopto-Student-Submission#10]
A raw json array is passed to contentitem_return.php, which is then extracted and the contents written directly in-line on the page as Javascript - it would be pretty trivial to inject extra javascript on the page.

Before using each item extracted from the json array, you should clean it/check it's expected type

**Comment by jmalmsten-panopto** [comment]
Hi,

This issue should be fixed with the latest release.

Thanks,
Joe
