### ISSUE TITLE
submissions_table class does not follow naming conventions

### ISSUE THREAD

**Issue by danmarsden** [Panopto/Moodle-Panopto-Student-Submission#11]
classes must be namespaced or follow our frankenstyle naming conventions as per:
https://docs.moodle.org/dev/Frankenstyle#Class_names

Note - this is a blocker for approval. Please check your classes are either namespaced or prefixed with "panoptosubmission"

**Comment by jmalmsten-panopto** [comment]
Hi,

This issue should be fixed with the latest release.

Thanks,
Joe
