### ISSUE TITLE
consider using require_sesskey() instead of your own exception

### ISSUE THREAD

**Issue by danmarsden** [Panopto/Moodle-Panopto-Student-Submission#13]
https://github.com/Panopto/Moodle-Panopto-Student-Submission/blob/master/submission.php#L28-L30

could just be one line:
```
require_sesskey();
```

(not a blocker for approval feel free to close as won't fix.)

**Comment by jmalmsten-panopto** [comment]
Hi,

This issue should be fixed with the latest release.

Thanks,
Joe
