### ISSUE TITLE
view_submission.php mixes functions and inline code

### ISSUE THREAD

**Issue by danmarsden** [Panopto/Moodle-Panopto-Student-Submission#14]
the view_submission.php file should not contain both functions and inline code - the "init_panoptosubmission_view()" function should be in a lib file somewhere (and named correctly with the frankenstyle prefix)

**Comment by jmalmsten-panopto** [comment]
Hi Dan,

I have made an internal work item for all of these issues and we will handle them hopefully in the near future. I'm making a TFS item for all of them and I will mark them all, but I'm only commenting on this issue so I don't spam you. 

Thanks,
Joe

**Comment by danmarsden** [comment]
Haha spam away :-) I filter github emails pretty heavily :-)

**Comment by jmalmsten-panopto** [comment]
Hi,

This issue should be fixed with the latest release.

Thanks,
Joe
