### ISSUE TITLE
Issue with decimal grade values when using Rubrics

### ISSUE THREAD

**Issue by shaunt-nait** [Panopto/Moodle-Panopto-Student-Submission#16]
The data type on the table panoptosubmission_submission grade is int and should be a number. When grading with rubrics, If the total of the rubric is more than the assignment and not 100% the value is scaled by Moodle. 
Example: 
Assignment /10
Rubric 14/15 = .93
10 * .93 = 9.3 
insert record fails.

**Comment by jmalmsten-panopto** [comment]
Hi,

Thank you for discovering this issue, I have filed an internal work item to take a look at this issue and make a fix. 

Thank you,
Joe Malmsten

**Comment by jmalmsten-panopto** [comment]
Hi,

This issue should be fixed with the latest release.

Thanks,
Joe
