### ISSUE TITLE
install.xml hand-rolled

### ISSUE THREAD

**Issue by danmarsden** [Panopto/Moodle-Panopto-Student-Submission#3]
The install.xml is not completely valid and appears to have been handwritten.

This needs to be fixed using the Moodle xmldb editor (under admin > development > XMLDB.)

Please hit the "load" link for your plugin install.xml file in the moodle xmldb editor, and then make Moodle think there is an update to the file (easiest way to do this is to change the description of a table - add a full stop or something similar.) Then get XMLDB to "Save" the updated file which will remove all the old invalid xml from your file.

**Comment by jmalmsten-panopto** [comment]
Hi,

This issue should be fixed with the latest release.

Thanks,
Joe
