### ISSUE TITLE
thumbnail fields missing from backup api

### ISSUE THREAD

**Issue by danmarsden** [Panopto/Moodle-Panopto-Student-Submission#6]
looks like the thumbnail fields were added to install.xml but not the backup api - please check all database fields are correctly included in the backup apis.

**Comment by danmarsden** [comment]
.. in fact - looking at the code I think I can see a couple of undefined classes - would be good for you to make sure you test a backup/restore of a course that includes a panopto activity too.

**Comment by jmalmsten-panopto** [comment]
Hi,

This issue should be fixed with the latest release.

Thanks,
Joe
