### ISSUE TITLE
missing external_location_link definitiion in privacy api

### ISSUE THREAD

**Issue by danmarsden** [Panopto/Moodle-Panopto-Student-Submission#7]
I assume that there is some form of interaction with Moodle and Panopto, and some user information is shared between the two for sso or identification etc.. (I could be wrong) - but if I am correct, then you need to implement the external_location_link function in your privacy api as per:
https://docs.moodle.org/dev/Privacy_API#Indicating_that_you_export_data_to_an_external_location

**Comment by danmarsden** [comment]
I see a few expected type failures in my IDE within the privacy api class too - it would be good if you could test a delete and a request of data process for a user that has panopto data in a course to make sure you don't get any errors (keep an eye on the cron tasks which generate the data and make sure they don't report any errors in the panopto code.)

**Comment by jmalmsten-panopto** [comment]
Hi,

This issue should be fixed with the latest release.

Thanks,
Joe
